### ISSUE TITLE
word document

### ISSUE THREAD

**Issue by cmcsoftware** [teentechdpit/hotels#13]
Un template in doc cu niste place holders la care se face replace cu date din ReservationDto. apoi trimis pe mail la user cu cc la hotel

**Comment by RaduTuodr** [comment]
https://mkyong.com/java/java-read-and-write-microsoft-word-with-apache-poi/
https://www.smartbill.ro/resurse/documente/factura-online?gclid=Cj0KCQjwsZKJBhC0ARIsAJ96n3XHEvINiVgDYuuuJcFzTHay69ZqXhQKLvs9O2hO2Z_vcSItZeF8CYIaApkSEALw_wcB

**Comment by RaduTuodr** [comment]
Am terminat partea de trimitere a mailului, am pus un model de document pe discord. Multumesc Roberto ca m ai ajutat :*
